// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbWPeR4-Ek_Wj6Ans-KNua16WWqO6WqbI',
    appId: '1:731022300465:web:f87b2dea6a6319dcd58c10',
    messagingSenderId: '731022300465',
    projectId: 'todo-489806',
    authDomain: 'todo-489806.firebaseapp.com',
    storageBucket: 'todo-489806.firebasestorage.app',
    measurementId: 'G-VB9RFVL60K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8dHI9UTMO9j7loky7Ljpkex3_sETwYlE',
    appId: '1:731022300465:android:cbd4f052302e1cafd58c10',
    messagingSenderId: '731022300465',
    projectId: 'todo-489806',
    storageBucket: 'todo-489806.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDAjh-h4SUbO0i9QPUVr_yM6bKrjVVl8g',
    appId: '1:731022300465:ios:93845f9d763c8df6d58c10',
    messagingSenderId: '731022300465',
    projectId: 'todo-489806',
    storageBucket: 'todo-489806.firebasestorage.app',
    iosBundleId: 'com.example.todoReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDAjh-h4SUbO0i9QPUVr_yM6bKrjVVl8g',
    appId: '1:731022300465:ios:93845f9d763c8df6d58c10',
    messagingSenderId: '731022300465',
    projectId: 'todo-489806',
    storageBucket: 'todo-489806.firebasestorage.app',
    iosBundleId: 'com.example.todoReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbWPeR4-Ek_Wj6Ans-KNua16WWqO6WqbI',
    appId: '1:731022300465:web:ce778798ad91fa4ed58c10',
    messagingSenderId: '731022300465',
    projectId: 'todo-489806',
    authDomain: 'todo-489806.firebaseapp.com',
    storageBucket: 'todo-489806.firebasestorage.app',
    measurementId: 'G-PWT52WJ87Q',
  );

}